### ISSUE TITLE
Adjust rackdiag height units

### ISSUE THREAD

**Issue by useirc** [bithium/nwdiag#1]
Need units to be less tall. A 1U unit displays more like a 2U or 3U.

**Comment by bithium** [comment]
Hello mantlepro,

this is an unofficial clone of the project https://bitbucket.org/blockdiag/nwdiag/.

The official page for the project is http://blockdiag.com/en/.

Please post your question on the official issue tracker at https://bitbucket.org/blockdiag/blockdiag/issues?status=new&status=open.

Thank you.
